# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(902, 889)
        MainWindow.setLocale(QLocale(QLocale.Portuguese, QLocale.Brazil))
        self.actionSair = QAction(MainWindow)
        self.actionSair.setObjectName(u"actionSair")
        self.actionIndice = QAction(MainWindow)
        self.actionIndice.setObjectName(u"actionIndice")
        self.actionIn_cio = QAction(MainWindow)
        self.actionIn_cio.setObjectName(u"actionIn_cio")
        self.actionSobre = QAction(MainWindow)
        self.actionSobre.setObjectName(u"actionSobre")
        self.actionItalico = QAction(MainWindow)
        self.actionItalico.setObjectName(u"actionItalico")
        self.actionNegrito = QAction(MainWindow)
        self.actionNegrito.setObjectName(u"actionNegrito")
        self.actionSublinhado = QAction(MainWindow)
        self.actionSublinhado.setObjectName(u"actionSublinhado")
        self.actionC_digo = QAction(MainWindow)
        self.actionC_digo.setObjectName(u"actionC_digo")
        self.actionModo_sele_o = QAction(MainWindow)
        self.actionModo_sele_o.setObjectName(u"actionModo_sele_o")
        self.actionNavega_o = QAction(MainWindow)
        self.actionNavega_o.setObjectName(u"actionNavega_o")
        self.actionSele_o = QAction(MainWindow)
        self.actionSele_o.setObjectName(u"actionSele_o")
        self.actionC_digo_bloco = QAction(MainWindow)
        self.actionC_digo_bloco.setObjectName(u"actionC_digo_bloco")
        self.actionMesmo_nivel = QAction(MainWindow)
        self.actionMesmo_nivel.setObjectName(u"actionMesmo_nivel")
        self.actionNivel_abaixo = QAction(MainWindow)
        self.actionNivel_abaixo.setObjectName(u"actionNivel_abaixo")
        self.actionNivel_acima = QAction(MainWindow)
        self.actionNivel_acima.setObjectName(u"actionNivel_acima")
        self.action1 = QAction(MainWindow)
        self.action1.setObjectName(u"action1")
        self.action2 = QAction(MainWindow)
        self.action2.setObjectName(u"action2")
        self.action3 = QAction(MainWindow)
        self.action3.setObjectName(u"action3")
        self.action4 = QAction(MainWindow)
        self.action4.setObjectName(u"action4")
        self.action5 = QAction(MainWindow)
        self.action5.setObjectName(u"action5")
        self.action6 = QAction(MainWindow)
        self.action6.setObjectName(u"action6")
        self.actionInterno = QAction(MainWindow)
        self.actionInterno.setObjectName(u"actionInterno")
        self.actionInterno_2 = QAction(MainWindow)
        self.actionInterno_2.setObjectName(u"actionInterno_2")
        self.actionExterno = QAction(MainWindow)
        self.actionExterno.setObjectName(u"actionExterno")
        self.actionParquinho = QAction(MainWindow)
        self.actionParquinho.setObjectName(u"actionParquinho")
        self.actionPrefer_ncias = QAction(MainWindow)
        self.actionPrefer_ncias.setObjectName(u"actionPrefer_ncias")
        self.actionOp_es_de_desenvolvedor = QAction(MainWindow)
        self.actionOp_es_de_desenvolvedor.setObjectName(u"actionOp_es_de_desenvolvedor")
        self.actionCustomizado = QAction(MainWindow)
        self.actionCustomizado.setObjectName(u"actionCustomizado")
        self.actionPesquisar = QAction(MainWindow)
        self.actionPesquisar.setObjectName(u"actionPesquisar")
        self.actionVoltar = QAction(MainWindow)
        self.actionVoltar.setObjectName(u"actionVoltar")
        self.actionPosterior = QAction(MainWindow)
        self.actionPosterior.setObjectName(u"actionPosterior")
        self.actionRecarregar = QAction(MainWindow)
        self.actionRecarregar.setObjectName(u"actionRecarregar")
        self.actionMais = QAction(MainWindow)
        self.actionMais.setObjectName(u"actionMais")
        self.actionMenos = QAction(MainWindow)
        self.actionMenos.setObjectName(u"actionMenos")
        self.actionHist_rico = QAction(MainWindow)
        self.actionHist_rico.setObjectName(u"actionHist_rico")
        self.actionIn_cio_2 = QAction(MainWindow)
        self.actionIn_cio_2.setObjectName(u"actionIn_cio_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.webEngineView = QWebEngineView(self.centralwidget)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setLocale(QLocale(QLocale.Portuguese, QLocale.Brazil))
        self.webEngineView.setUrl(QUrl(u"about:blank"))

        self.verticalLayout_3.addWidget(self.webEngineView)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 902, 23))
        self.menuArquivo = QMenu(self.menubar)
        self.menuArquivo.setObjectName(u"menuArquivo")
        self.menuWiki = QMenu(self.menubar)
        self.menuWiki.setObjectName(u"menuWiki")
        self.menuZoom = QMenu(self.menuWiki)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuAjuda = QMenu(self.menubar)
        self.menuAjuda.setObjectName(u"menuAjuda")
        self.menuAjuda.setLocale(QLocale(QLocale.Portuguese, QLocale.Brazil))
        self.menuInserir = QMenu(self.menubar)
        self.menuInserir.setObjectName(u"menuInserir")
        self.menuModo = QMenu(self.menubar)
        self.menuModo.setObjectName(u"menuModo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuWiki.menuAction())
        self.menubar.addAction(self.menuInserir.menuAction())
        self.menubar.addAction(self.menuModo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.menuArquivo.addAction(self.actionPrefer_ncias)
        self.menuArquivo.addAction(self.actionSair)
        self.menuWiki.addAction(self.actionIn_cio_2)
        self.menuWiki.addAction(self.menuZoom.menuAction())
        self.menuWiki.addSeparator()
        self.menuWiki.addAction(self.actionHist_rico)
        self.menuWiki.addSeparator()
        self.menuWiki.addAction(self.actionCustomizado)
        self.menuWiki.addAction(self.actionPesquisar)
        self.menuWiki.addAction(self.actionVoltar)
        self.menuWiki.addAction(self.actionPosterior)
        self.menuWiki.addAction(self.actionRecarregar)
        self.menuWiki.addSeparator()
        self.menuZoom.addAction(self.actionMais)
        self.menuZoom.addAction(self.actionMenos)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuAjuda.addAction(self.actionOp_es_de_desenvolvedor)
        self.menuModo.addAction(self.actionNavega_o)
        self.menuModo.addAction(self.actionSele_o)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pesto", None))
        self.actionSair.setText(QCoreApplication.translate("MainWindow", u"Sair", None))
        self.actionIndice.setText(QCoreApplication.translate("MainWindow", u"Indice", None))
        self.actionIn_cio.setText(QCoreApplication.translate("MainWindow", u"In\u00edcio", None))
        self.actionSobre.setText(QCoreApplication.translate("MainWindow", u"Sobre", None))
        self.actionItalico.setText(QCoreApplication.translate("MainWindow", u"Italico", None))
        self.actionNegrito.setText(QCoreApplication.translate("MainWindow", u"Negrito", None))
        self.actionSublinhado.setText(QCoreApplication.translate("MainWindow", u"Sublinhado", None))
        self.actionC_digo.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo", None))
        self.actionModo_sele_o.setText(QCoreApplication.translate("MainWindow", u"Modo sele\u00e7\u00e3o", None))
        self.actionNavega_o.setText(QCoreApplication.translate("MainWindow", u"Navega\u00e7\u00e3o", None))
        self.actionSele_o.setText(QCoreApplication.translate("MainWindow", u"Sele\u00e7\u00e3o", None))
        self.actionC_digo_bloco.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo (bloco)", None))
        self.actionMesmo_nivel.setText(QCoreApplication.translate("MainWindow", u"Mesmo nivel", None))
        self.actionNivel_abaixo.setText(QCoreApplication.translate("MainWindow", u"Nivel abaixo", None))
        self.actionNivel_acima.setText(QCoreApplication.translate("MainWindow", u"Nivel acima", None))
        self.action1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.action5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.action6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.actionInterno.setText(QCoreApplication.translate("MainWindow", u"Interno", None))
        self.actionInterno_2.setText(QCoreApplication.translate("MainWindow", u"Interno", None))
        self.actionExterno.setText(QCoreApplication.translate("MainWindow", u"Externo", None))
        self.actionParquinho.setText(QCoreApplication.translate("MainWindow", u"Parquinho", None))
        self.actionPrefer_ncias.setText(QCoreApplication.translate("MainWindow", u"Prefer\u00eancias", None))
        self.actionOp_es_de_desenvolvedor.setText(QCoreApplication.translate("MainWindow", u"Op\u00e7\u00f5es de desenvolvedor", None))
        self.actionCustomizado.setText(QCoreApplication.translate("MainWindow", u"Ir", None))
        self.actionPesquisar.setText(QCoreApplication.translate("MainWindow", u"Pesquisar", None))
        self.actionVoltar.setText(QCoreApplication.translate("MainWindow", u"Anterior", None))
        self.actionPosterior.setText(QCoreApplication.translate("MainWindow", u"Posterior", None))
        self.actionRecarregar.setText(QCoreApplication.translate("MainWindow", u"Recarregar", None))
        self.actionMais.setText(QCoreApplication.translate("MainWindow", u"Mais", None))
        self.actionMenos.setText(QCoreApplication.translate("MainWindow", u"Menos", None))
        self.actionHist_rico.setText(QCoreApplication.translate("MainWindow", u"Hist\u00f3rico", None))
        self.actionIn_cio_2.setText(QCoreApplication.translate("MainWindow", u"In\u00edcio", None))
        self.menuArquivo.setTitle(QCoreApplication.translate("MainWindow", u"Arquivo", None))
        self.menuWiki.setTitle(QCoreApplication.translate("MainWindow", u"Navega\u00e7\u00e3o", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.menuAjuda.setTitle(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.menuInserir.setTitle(QCoreApplication.translate("MainWindow", u"Atalhos", None))
        self.menuModo.setTitle(QCoreApplication.translate("MainWindow", u"Modo", None))
    # retranslateUi

